#!/opt/bin/php
<?php declare(strict_types=1); declare(ticks=1);

chdir(getenv('KUBELESS_INSTALL_VOLUME')) or die('Unable to change to kubeless install volume');
require './vendor/autoload.php';
require './bootstrap/app.php';

use Laravel\Serverless\Application;
use Laravel\Serverless\Kubeless\Proxy;
use Laravel\Serverless\Kubeless\RequestFactory;

Proxy::start(function(array $event, array $context, Proxy $proxy) {
    switch($context['function-name']) {
        case 'artisan':
            $args = (array) $event['data'];
            if (! $args) {
                $args = ['schedule:run', '--no-ansi', '--no-interaction'];
            } elseif (
                array_key_exists('displayName', $args) &&
                array_key_exists('job', $args) &&
                array_key_exists('data', $args)
            ) {
                $args = ['serverless:work', base64_encode(json_encode($args))];
            }

            $proxy->log(sprintf(
                'CLI %s', serialize($args)
            ));

            list($status, $output) = Application::artisan(array_merge(
                [__FILE__], $args
            ));

            if ($status !== 0) {
                throw new \RuntimeException($output);
            }

            return $output;
        case 'website':
            $request = RequestFactory::fromPayload($event);
            $proxy->log(sprintf(
                'WEB %s %s', $request->getMethod(), $request->getRequestUri()
            ));
            return Application::website($request);
        default:
            throw new RuntimeException("Unknown function ${context['function-name']}");
    }
});
