# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: workbench

provider:
  name: kubeless
  runtime: workbench7.2
  namespace: workbench
  environment:
    LOG_CHANNEL: 'stderr'
    #QUEUE_CONNECTION: 'kafka'
    #KAFKA_QUEUE: 'workbench_default'
    #KAFKA_BROKERS: 'kafka.kubeless.svc:9092'
    QUEUE_CONNECTION: 'nats'
    NATS_SERVER: 'nats://nats_client:tOnDjH4oEm@nats-client.nats-system.svc:4222'
    NATS_TOPIC: workbench-default-topic
  ingress:
    class: "traefik"
  deploy:
    strategy: S3ZipContent
    options:
      accessKeyId: minio
      secretAccessKey: minio123
      endpoint: http://minio.k3s.kvm
      bucket: workbench
      region: eu-central-1
      s3ForcePathStyle: True

package:
  exclude:
    - .idea/**
    - .git/**
    - storage/**
    - node_modules/**
    - bootstrap/cache/*.php
    - tests/**
    - vendor/**
  include:
    - storage/app/public/.gitignore
    - storage/framework/cache/data/.gitignore
    - storage/framework/sessions/.gitignore
    - storage/framework/views/.gitignore

plugins:
  - ./vendor/vognev/laravel-serverless-kubeless/plugin/index.js

functions:
  website:
    handler: laravel.website
    memorySize: 1024
    cpu: 1000m
    events:
      - http:
          hostname: workbench.k3s.kvm
  artisan:
    handler: laravel.artisan
    memorySize: 1024
    cpu: 1000m
    events:
      - schedule: "* * * * *"
      #- trigger: 'workbench_default'
